// svgo.config.js
module.exports = {
  plugins: [
    "removeDoctype",
    "removeXMLProcInst",
    "removeComments",
    "removeMetadata",
    // 'removeXMLNS',
    "removeEditorsNSData",
    "cleanupAttrs",
    "inlineStyles",
    "minifyStyles",
    "convertStyleToAttrs",
    // 'cleanupIDs',
    "cleanupIds",
    // 'removeRasterImages',
    // 'removeUnusedDefs',
    "removeUselessDefs",
    "convertPathData",
    "convertTransform",
    "removeUnknownsAndDefaults",
    "removeUselessStrokeAndFill",
    // 'removeViewBox',
    "cleanupEnableBackground",
    "removeHiddenElems",
    "removeEmptyText",
    "convertShapeToPath",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "collapseGroups",
    "convertPathData",
    "convertTransform",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "mergePaths",
    "removeUnusedNS",
    // 'sortAttrs',
    "removeTitle",
    "removeDesc",
    // 'removeDimensions',
    // "removeStyleElement",
    // 'removeScriptElement',
  ],
};
